import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const heraldic = localFont({
  src: '../../src/assets/fonts/Heraldic-Shadows.otf',
  variable: '--font-heraldic',
});

const luxury = localFont({
  src: '../../src/assets/fonts/Modern-Luxury.ttf',
  variable: '--font-luxury',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${heraldic.variable} ${luxury.variable}`}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
